import { MessagePort, Worker } from "worker_threads";

/**
 * Represents the options for file conversion.
 *
 * @property {string} input - The path to the input file.
 * @property {string} output - The path to the output file.
 * @property {boolean} delete - Whether to delete the input file after conversion. Defaults to false.
 * @property {boolean} silent - Whether to suppress output during conversion. Defaults to true.
 * @property {low | med | high} verbose - The verbosity level of the calibre conversion process. Defaults to low.
 */
export interface ConversionOptions {
    input: string;
    output: string;
    delete: boolean;
    silent: boolean;
    verbose?: "low" | "med" | "high";
}

/**
 * Represents the result of a conversion operation.
 *
 * @property success - Indicates whether the conversion was successful.
 * @property outputPath - The path to the output file generated by the conversion.
 * @property [error] - An optional error message if the conversion failed.
 */
export interface ConversionResult {
    success: boolean;
    outputPath: string;
    error?: string;
}

export interface WorkerItem {
    worker: Worker;
    port: MessagePort;
    options: ConversionOptions;
}